//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJE_Deneme_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hasta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hasta()
        {
            this.Randevu = new HashSet<Randevu>();
        }
    
        public int HastaID { get; set; }
        public string HastaAdi { get; set; }
        public string HastaSoyadi { get; set; }
        public string TCKN { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public Nullable<decimal> Kilo { get; set; }
        public string Cinsiyet { get; set; }
        public string HastaTelefonNo { get; set; }
        public string HastaMail { get; set; }
        public string HastaAdres { get; set; }
        public Nullable<int> HastaGecmisiID { get; set; }
        public string KanGrubuID { get; set; }
        public Nullable<bool> HastaDurum { get; set; }
    
        public virtual Cinsiyet Cinsiyet1 { get; set; }
        public virtual HastaGecmisi HastaGecmisi { get; set; }
        public virtual KanGrubu KanGrubu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevu> Randevu { get; set; }
    }
}
