//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJE_Deneme_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaGecmisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HastaGecmisi()
        {
            this.Hasta = new HashSet<Hasta>();
        }
    
        public int HastaGecmisiID { get; set; }
        public string KullandigiIlac { get; set; }
        public string GecirdigiHastalik { get; set; }
        public string GecirdigiAmeliyat { get; set; }
        public string Alerjiler { get; set; }
        public Nullable<bool> HastaGecmisiDurum { get; set; }
        public Nullable<int> HastaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hasta> Hasta { get; set; }
    }
}
