//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJE_Deneme_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilaclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ilaclar()
        {
            this.ReceteDetay = new HashSet<ReceteDetay>();
        }
    
        public int BarkodID { get; set; }
        public string IlacAdi { get; set; }
        public string İcerikBilgi { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceteDetay> ReceteDetay { get; set; }
    }
}
