//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJE_Deneme_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HastaneOtomasyonEntities : DbContext
    {
        public HastaneOtomasyonEntities()
            : base("name=HastaneOtomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cinsiyet> Cinsiyet { get; set; }
        public virtual DbSet<Doktorlar> Doktorlar { get; set; }
        public virtual DbSet<Hasta> Hasta { get; set; }
        public virtual DbSet<HastaGecmisi> HastaGecmisi { get; set; }
        public virtual DbSet<HastaneBilgi> HastaneBilgi { get; set; }
        public virtual DbSet<Ilaclar> Ilaclar { get; set; }
        public virtual DbSet<Izinler> Izinler { get; set; }
        public virtual DbSet<KanGrubu> KanGrubu { get; set; }
        public virtual DbSet<Meslek> Meslek { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Poliklinik> Poliklinik { get; set; }
        public virtual DbSet<Randevu> Randevu { get; set; }
        public virtual DbSet<ReceteDetay> ReceteDetay { get; set; }
        public virtual DbSet<RandevuDetay> RandevuDetay { get; set; }
        public virtual DbSet<SifrelerVeHashler> SifrelerVeHashler { get; set; }
    }
}
