//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJE_Deneme_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Doktorlar = new HashSet<Doktorlar>();
            this.Izinler = new HashSet<Izinler>();
        }
    
        public int PersonelID { get; set; }
        public Nullable<int> MeslekID { get; set; }
        public string PersonelAdi { get; set; }
        public string PersonelSoyadi { get; set; }
        public string TCKN { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Cinsiyet { get; set; }
        public string TelefonNo { get; set; }
        public string Mail { get; set; }
        public string Adres { get; set; }
        public System.DateTime İseGirisTarihi { get; set; }
        public string EnSonMezuniyetBilgisi { get; set; }
        public string KanGrubuID { get; set; }
        public int HastaneID { get; set; }
        public Nullable<bool> PersonelDurum { get; set; }
        public string Sifre { get; set; }
    
        public virtual Cinsiyet Cinsiyet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doktorlar> Doktorlar { get; set; }
        public virtual HastaneBilgi HastaneBilgi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izinler> Izinler { get; set; }
        public virtual KanGrubu KanGrubu { get; set; }
        public virtual Meslek Meslek { get; set; }
        public override string ToString()
        {
            return PersonelAdi + " >> " + PersonelSoyadi + " >> " + Meslek.MeslekTuru + " >> " + İseGirisTarihi + " >> " + Sifre;
        }
    }
}
