//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJE_Deneme_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SifrelerVeHashler
    {
        public int ID { get; set; }
        public string Sifre { get; set; }
        public string Hash { get; set; }
        public Nullable<int> PersonelID { get; set; }
    }
}
